apiVersion: v1
kind: Service
metadata:
  name: monitoring
  namespace: xp-panel
  labels:
    app: monitoring
    app.kubernetes.io/component: monitoring
spec:
  selector:
    app: monitoring
  ports:
    - name: http
      port: 8088
      targetPort: 8088
      protocol: TCP
  type: ClusterIP
