apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: xp-panel
  labels:
    app: notification
    app.kubernetes.io/component: notification
spec:
  selector:
    app: notification
  ports:
    - name: http
      port: 8094
      targetPort: 8094
      protocol: TCP
  type: ClusterIP
