apiVersion: v1
kind: Service
metadata:
  name: dns
  namespace: xp-panel
  labels:
    app: dns
    app.kubernetes.io/component: dns
spec:
  selector:
    app: dns
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
