apiVersion: v1
kind: Service
metadata:
  name: billing
  namespace: xp-panel
  labels:
    app: billing
    app.kubernetes.io/component: billing
spec:
  selector:
    app: billing
  ports:
    - name: http
      port: 8089
      targetPort: 8089
      protocol: TCP
  type: ClusterIP
