all:
  children:
    web_servers:
      hosts:
        server1:
          ansible_host: "{{ lookup('env','SERVER_IP') | default('YOUR_SERVER_IP') }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
