apiVersion: v1
kind: Service
metadata:
  name: mail
  namespace: xp-panel
  labels:
    app: mail
    app.kubernetes.io/component: mail
spec:
  selector:
    app: mail
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP
