apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: xp-panel
  labels:
    app: gateway
    app.kubernetes.io/component: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
