apiVersion: v1
kind: Service
metadata:
  name: backup
  namespace: xp-panel
  labels:
    app: backup
    app.kubernetes.io/component: backup
spec:
  selector:
    app: backup
  ports:
    - name: http
      port: 8087
      targetPort: 8087
      protocol: TCP
  type: ClusterIP
